server:
  error:
    include-stacktrace: ALWAYS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"